services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysqlv57
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3305:3306'
    volumes:
      - './data:/var/lib/mysql'
      - './conf/my.cnf:/etc/mysql/conf.d/my.cnf'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s