services:
  postgresql:
    image: postgres:18
    container_name: postgresqlv18
    ports:
      - '5432:5432'
    volumes:
      - './data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s